<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun = rerun.strip.gsub /\s/, ' '
rerun_opts = rerun.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags 'not @wip'"
time = Time.now.strftime('%Y%m%d_%H%M%S').to_s
%>
default: <%= std_opts %> features -p html_report -p json_report
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags 'not @wip'
html_report: --format pretty --format html --out=features/reports/features_report_<%=time%>.html
json_report: --format pretty --format json --out=features/reports/features_report_<%=time%>.json
